Repository spbu-math-cs/roomkn, pull requests merged in 2023-11, with the labels that each got.

#179 Fix cleanup thread launching/stopping
  server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountController.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountControllerImpl.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/plugins/CleanupThreads.kt
Labels: bug

#184 Update/Delete for users
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/models/users/UpdateUserInfo.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/DatabaseTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
Labels: back-end

#185 Reservations admin
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ApiRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/models/Conversations.kt
Labels: back-end

#176 Add reservation stress test
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseExceptions.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/database/DatabaseTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/database/ReservationStressTest.kt
Labels: back-end, database

#175 Openapi документация
  server/docs/README.md
  server/docs/api.md
  server/docs/api/openapi-release-0.0.1.yaml
  server/docs/configuration.md
  server/docs/getting_started.md
  server/docs/swagger/docker-compose.yml
Labels: documentation

#214 Remove permissions from cookie
  server/build.gradle.kts
  server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountControllerImpl.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthConfig.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/plugins/CallLogging.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
Labels: bug, back-end
