Repository spbu-math-cs/roomkn, pull requests merged in 2023-12, with the labels that each got.

#264 change response for POST /register
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
Labels: back-end

#268 Replace alerts to snackbars
  client/src/App.js
  client/src/components/Navbar.js
  client/src/components/SnackbarAlert.js
  client/src/pages/Profile.js
  client/src/pages/Room.js
  client/src/pages/SignIn.js
  client/src/pages/SignUp.js
  client/src/pages/UserReservation.js
Labels: front-end

#213 add GET /reserve with query params
  server/docs/api/openapi-release-0.0.1.yaml
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
Labels: documentation, back-end

#266 Map in server
  server/docs/api/openapi-release-0.0.1.yaml
  server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/plugins/defaultMapCreation.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
Labels: back-end, database

#267 Moved timeline to particular file
  client/src/components/Timeline.css
  client/src/components/Timeline.js
  client/src/pages/Room.css
  client/src/pages/Room.js
Labels: front-end

#237 Client-only map
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar.js
  client/src/pages/Map.js
  client/src/pages/MapData.js
Labels: front-end

#262 Made currentUser fully update on getting username
  client/src/components/Auth.js
  client/src/components/Timeline.js
Labels: front-end

#299 Fixed my reservations page
  client/src/pages/UserReservation.js
Labels: front-end

#292 Add DatePickers and disable too long time periods show in List
  client/package-lock.json
  client/package.json
  client/src/components/TimelineForRoomList.css
  client/src/components/TimelineForRoomList.js
  client/src/pages/List.js
  client/src/pages/Room.js
Labels: front-end

#297 Fix timeline in room list
  client/src/App.js
  client/src/components/TimelineForRoomList.css
  client/src/components/TimelineForRoomList.js
  client/src/pages/List.css
  client/src/pages/List.js
Labels: front-end

#358 Add order parameters to GET /reservations
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/ReservationSortParameter.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
Labels: back-end

#363 Limitations for reservations in far past/future
  server/src/main/kotlin/org/tod87et/roomkn/server/di/ReservationConfig.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Koin.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
  server/src/main/resources/application.conf
  server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
Labels: back-end

#341 Invite in server
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/models/users/Invite.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/models/users/InviteRequest.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/AuthTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
  server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
Labels: back-end

#379 Fix ReservationConfig initialization
  server/src/main/kotlin/org/tod87et/roomkn/server/di/ReservationConfig.kt
Labels: bug, back-end

#388 Disable cors in prod
  server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
  server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Cors.kt
  server/src/main/resources/dev.conf
Labels: back-end
